noQ-sweden/noq

.github/workflows/noq_deployment.yml
Added needed steps in deployment workflow to validate backend build before starting deployment to Development
=> Added steps for build validation of backend

.github/workflows/noq_deployment.yml, noq-backend/Dockerfile, noq-backend/pom.xml, noq-backend/src/main/java/com/noq/backend/models/Bed.java
Added needed deployment steps for backend app to verify build and also adjusted Dockerfile to have separate build step.
=> Deployment steps for backend app

.github/workflows/noq-pr-validation.yml, noq-backend/Dockerfile
Corrections to backend docker file and addition of PR build validation workflow
=> Corrections to backend docker file

noq-backend/src/main/java/com/noq/backend/models/Bed.java, noq-backend/src/main/java/com/noq/backend/models/Host.java, noq-backend/src/main/java/com/noq/backend/repository/BedRepository.java
Work in progress on controllers and services.
=> Some minor changes and some comments.

noq-backend/src/main/java/com/noq/backend/controllers/HostController.java, noq-backend/src/main/java/com/noq/backend/controllers/ReservationController.java, noq-backend/src/main/java/com/noq/backend/models/Address.java, noq-backend/src/main/java/com/noq/backend/models/Host.java, noq-backend/src/main/java/com/noq/backend/services/HostService.java
Created mock-data to return for testing (a array of 2 hosts)
endpoint /api/host/getall now treturns mock data for 2 host locations! see pic in JIRA.
Please give me feedback on this! :)
=> Created a HostService and a HostController,

noq-backend/src/main/java/com/noq/backend/controllers/UserController.java, noq-backend/src/main/java/com/noq/backend/models/User.java, noq-backend/src/main/java/com/noq/backend/services/UserService.java
Created mock-data to return for testing (a array of 2 Users, one with reservation=false and one with reservation=true)
Please give me feedback on this! :)
=> Created a UserService and a UserController,

frontend/react/Dockerfile, frontend/react/src/App.tsx
Small fix to front end app to render ok. Small tweeks to docker file to run smaller nginx image after build
=> Small fix to front end app and docker file

.github/workflows/noq_deployment.yml, infrastructure/noq-container-app.bicep
Fixed port settings on app provision
=> Fixed port settings on app provision

.github/dependabot.yml, infrastructure/noq-container-app.bicep, infrastructure/resource-templates/container-app-template.bicep
Adding Dependabot scan and more CORS fixes for backend app
=> Dependabot and CORS fixes

CODE_OF_CONDUCT.md
Completion of Code Of Conduct document which cover #NOQ-16 in Jira.
=> Code of Conduct document

frontend/react/package-lock.json, frontend/react/package.json, frontend/react/src/interfaces/IHost.ts, frontend/react/src/pages/VacantBedPage.tsx
VacantBedPage ui completed. Data is hardcoded inside the component atm since the fetch doenst work with the container. 
Also added react icons to the project
=> Kevin vacant beds page

noq-backend/src/main/java/com/noq/backend/DTO/HostDTO.java, noq-backend/src/main/java/com/noq/backend/DTO/UserDTO.java, noq-backend/src/main/java/com/noq/backend/controllers/HostController.java, noq-backend/src/main/java/com/noq/backend/controllers/UserController.java, noq-backend/src/main/java/com/noq/backend/models/Host.java
Unsure if we include id In DTO, would like some feedback on this!
Safe to Merge though, everything works!
=> Added DTOs to User and Host entitys.

.github/workflows/noq-dependency-review.yml, .github/workflows/noq-pr-validation.yml, infrastructure/README.md, noq-backend/Dockerfile
Added workflow for dependency review during PR to make sure we dont introduce third party libraries that have known vulnerabilities. Also added some additional documentation around what workflows are executed during PR review.
=> Continues integration improvments

frontend/react/src/views/Login.tsx
Fixed issue on LoginPage where backticks were missing on a string with a declared variable.
This issue prevented any user to login.
=> Axios_get_request_string_missing_backticks

frontend/react/src/pages/guest/components/MessageToClientComponent.tsx, frontend/react/src/pages/guest/views/vacanciesView/VacanciesView.tsx
Changes done to the vacancy side where the client can only book one bed for the night, if client has already booked a bed - an error message will appear.
=> NOQ-148 If reservation has been made, don't show vacanciesView, show appropriate message

frontend/react/src/pages/guest/views/vacanciesView/VacanciesView.tsx
Found a bug where the states were inverted. Solved by changing false to true.
=> buggfix-noQ#148

noq-backend/src/main/java/com/noq/backend/DTO/cosmos/HostCosmosDTO.java, noq-backend/src/main/java/com/noq/backend/DTO/cosmos/VacancyViewCosmosDTO.java, noq-backend/src/main/java/com/noq/backend/controllers/cosmos/ReservationsViewCosmosController.java, noq-backend/src/main/java/com/noq/backend/models/cosmos/AddressCosmos.java, noq-backend/src/main/java/com/noq/backend/models/cosmos/HostCosmos.java, noq-backend/src/main/java/com/noq/backend/services/InitializeDataService.java, noq-backend/src/main/java/com/noq/backend/services/cosmos/HostCosmosService.java
Created AdressCosmos without ID.
Created InitializeDataService for Cosmos Host, user.
=> REAFACTOR -

.github/workflows/noq_deployment.yml
Fixed ingress ports on admin and host client apps
=> Fixed container ingress ports on admin and host client apps

frontend/user-client/src/app/bookings/[...slug]/page.tsx, frontend/user-client/src/components/bookings/Bookings.tsx, frontend/user-client/src/components/bookings/BookingsPageDTO.tsx, frontend/user-client/src/layouts/Header.tsx, frontend/user-client/src/layouts/Layout.tsx, frontend/user-client/src/layouts/SideMenuLargeScreen.tsx
=> added sort list

frontend/host-client/src/components/requests/Requests.tsx, frontend/host-client/src/components/requests/RequestsAPI.tsx, frontend/host-client/src/components/requests/RequestsPageDTO.tsx, frontend/user-client/src/components/available-hosts/components/AvailableBookingItem.tsx, frontend/user-client/src/components/booking/BookingPageAPI.tsx, noq-backend/src/main/java/com/noq/backend/clients/host/bookings/BookingsPageController.java, noq-backend/src/main/java/com/noq/backend/clients/host/bookings/reqBody/BookingApprovalDTO.java, noq-backend/src/main/java/com/noq/backend/clients/host/bookings/reqBody/BookingApprovalReqBody.java, noq-backend/src/main/java/com/noq/backend/clients/user/availableHosts/UserAvailableHostsController.java, noq-backend/src/main/java/com/noq/backend/clients/user/availableHosts/UserAvailableHostsDTO.java, noq-backend/src/main/java/com/noq/backend/clients/user/booking/UserBookingController.java, noq-backend/src/main/java/com/noq/backend/clients/user/booking/UserCreateBookingRequestDto.java, noq-backend/src/main/java/com/noq/backend/clients/user/booking/reqbody/UserCreateBookingRequestDTO.java, noq-backend/src/main/java/com/noq/backend/clients/user/myBookings/MyBookingsController.java, noq-backend/src/main/java/com/noq/backend/repositories/BookingRepository.java, noq-backend/src/main/java/com/noq/backend/services/HostService.java
run again - it shouldn't throw error as it passed in this PR
=> Revert "added deny and approve booking now works"
